# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 76ff5170dfde0ca58ae5dca4db75b01d6f1c696494ea05d330f2ed235e77b3093bb6719a3ba2b33f3c240cceb9d4bdf1fdec6ce20885e0e4d95415cbea289d95

test:
  secret_key_base: d80751f557948960c5ac181f4c88eadde65e75c9ddd556d5a21956c5ee3c7a5b2eb5432b3fc7941e2860c18ef31551a742b52ade77eba8d6a5769f3cc407fdf8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
